steps:

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-k', './production/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cicd'

options:
  machineType: 'N1_HIGHCPU_8'
timeout: 720s