apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo-api
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-app
        image: demo-app-image
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 8080
