apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: demo-app-image
  newName: savaninirav/gke-demo-app
  newTag: f746bca
resources:
- namespace.yaml
- demo-api-deployment.yaml
- demo-api-service.yaml
